<?php

namespace ItemBundle\Repository;

/**
 * ArmorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorRepository extends \Doctrine\ORM\EntityRepository
{
}
