<?php

namespace ItemBundle\Repository;

/**
 * ClothingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClothingRepository extends \Doctrine\ORM\EntityRepository
{
}
