<?php

namespace ItemBundle\Repository;

/**
 * CommonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonRepository extends \Doctrine\ORM\EntityRepository
{
}
