<?php

namespace ItemBundle\Repository;

/**
 * HerbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HerbRepository extends \Doctrine\ORM\EntityRepository
{
}
