<?php

namespace ItemBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllCategories(){
        $items = $this->findAll();

        $all_categories = array();

        foreach($items as $item){
            if(!in_array($item->getType(),$all_categories))
                $all_categories[$item->getType()] = array(
                    'className' => $item->getClassName(),
                    'repositoryNaming' => $item->getRepositoryNaming(),
                );
        }

        return $all_categories;
    }

}
