<?php

namespace ItemBundle\Repository;

/**
 * ShieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShieldRepository extends \Doctrine\ORM\EntityRepository
{
}
