<?php

namespace ItemBundle\Repository;

/**
 * SpeAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
