<?php

namespace ItemBundle\Repository;

/**
 * SpecifiedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecifiedItemRepository extends \Doctrine\ORM\EntityRepository
{
}
