<?php

namespace ItemBundle\Repository;

/**
 * SpeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeItemRepository extends \Doctrine\ORM\EntityRepository
{
}
