<?php

namespace ItemBundle\Repository;

/**
 * SpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeRepository extends \Doctrine\ORM\EntityRepository
{
}
