easy_admin:
    site_name: 'Ryuutama Compendium'
    design:
        templates:
            field_string: ':easy_admin:field_string.html.twig'
        menu:
            - label: 'admin.menu.equipment'
              children: ['Weapon', 'Armor', 'Shield', 'Clothing']
            - label: 'admin.menu.animal'
              children: ['Carrier', 'Mount', 'Pet']
            - label: 'admin.menu.spe'
              children: ['SpeAnimal', 'SpeItem']
            - label: 'admin.menu.spell'
              children: ['SeasonalSpell', 'IncantationSpell']
            - Common
            - Container
            - Herb
            - SpecifiedItem
            - Job
            - Skill
    list:
        actions:
            - { name: 'show', label: 'action.show' }
            - { name: 'edit', label: 'action.edit' }
            - { name: 'delete', label: 'action.delete' }
    entities:
        Weapon:
            class: ItemBundle\Entity\Weapon
            list:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location' }
                    - { property: accuracy, label: 'admin.weapon.accuracy' }
                    - { property: damage, label: 'admin.weapon.damage' }
            form:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location', type: 'ItemBundle\Form\Type\LocationSelectType' }
                    - { property: accuracy, label: 'admin.weapon.accuracy' }
                    - { property: damage, label: 'admin.weapon.damage' }
                    - { property: description, label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        Armor:
            class: ItemBundle\Entity\Armor
            list:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location' }
                    - { property: defense_points, label: 'admin.armor.defense_points', sortable: true }
                    - { property: penality, label: 'admin.armor.penality' }
            form:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location', type_options: { attr: { readonly: true }}, type: 'ItemBundle\Form\Type\LocationSelectType'}
                    - { property: defensePoints, label: 'admin.armor.defense_points', sortable: true }
                    - { property: penality, label: 'admin.armor.penality' }
                    - { property: description, label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        Shield:
            class: ItemBundle\Entity\Shield
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location' }
                    - { property: 'defensePoints', label: 'admin.shield.defense_points', sortable: true }
                    - { property: 'penality', label: 'admin.shield.penality' }
                    - { property: 'dodgeValue', label: 'admin.shield.dodge_value', sortable: true }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location', type_options: { attr: { readonly: true }}, type: 'ItemBundle\Form\Type\LocationSelectType'}
                    - { property: 'defensePoints', label: 'admin.shield.defense_points', sortable: true }
                    - { property: 'penality', label: 'admin.shield.penality' }
                    - { property: 'dodgeValue', label: 'admin.shield.dodge_value', sortable: true }
                    - { property: 'description', label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        Clothing:
            class: ItemBundle\Entity\Clothing
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location', type: 'ItemBundle\Form\Type\LocationSelectType' }
                    - { property: 'description', label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }

        Carrier:
            class: ItemBundle\Entity\Carrier
        Mount:
            class: ItemBundle\Entity\Mount
        Pet:
            class: ItemBundle\Entity\Pet
        SpeAnimal:
            class: ItemBundle\Entity\SpeAnimal
            list:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'priceModifier', label: 'admin.spe.price_modifier' }
            form:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'priceModifier', label: 'admin.spe.price_modifier', type: 'ItemBundle\Form\Type\ModifierType' }
                    - { property: 'bonusModifiers', label: 'admin.spe.bonus_modifiers', type: 'collection', type_options: { entry_type: 'ItemBundle\Form\Type\BonusModifierType' } }
                    - { property: 'description', label: 'admin.item.description' }
        SpeItem:
            class: ItemBundle\Entity\SpeItem
            list:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'priceModifier', label: 'admin.spe.price_modifier' }
            form:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'priceModifier', label: 'admin.spe.price_modifier', type: 'ItemBundle\Form\Type\ModifierType' }
                    - { property: 'bonusModifiers', label: 'admin.spe.bonus_modifiers', type: 'collection', type_options: { entry_type: 'ItemBundle\Form\Type\BonusModifierType' } }
                    - { property: 'description', label: 'admin.item.description' }
        Herb:
            class: ItemBundle\Entity\Herb
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'part', label: 'admin.herb.part' }
                    - { property: 'level', label: 'admin.herb.level' }
                    - { property: 'terrain', label: 'admin.herb.terrain' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'effect', label: 'admin.herb.effect' }
                    - { property: 'part', label: 'admin.herb.part' }
                    - { property: 'level', label: 'admin.herb.level' }
                    - { property: 'terrain', label: 'admin.herb.terrain' }
                    - { property: 'description', label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        Common:
            class: ItemBundle\Entity\Common
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                actions: ['show', 'edit', 'delete']
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'description', label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        Container:
            class: ItemBundle\Entity\Container
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'capacity', label: 'admin.container.capacity' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'capacity', label: 'admin.container.capacity' }
                    - { property: 'description', label: 'admin.item.description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
        SpecifiedItem:
            class: ItemBundle\Entity\SpecifiedItem
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                actions:
                    - { name: 'show', label: 'action.show' }
                    - { name: 'delete', label: 'action.delete' }
            show:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'description', label: 'admin.item.description' }
            disabled_actions: ['new', 'edit']
        SeasonalSpell:
            class: CharacterBundle\Entity\SeasonalSpell
            list:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach' }
                    - { property: 'type', label: 'admin.spell.type' }
                    - { property: 'season', label: 'admin.spell.season' }
            form:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level', type: 'CharacterBundle\Form\Type\SpellLevelSelectType' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach', type: 'CharacterBundle\Form\Type\ReachSelectType' }
                    - { property: 'effect', label: 'admin.spell.effect' }
                    - { property: 'type', label: 'admin.spell.type', type: 'CharacterBundle\Form\Type\SpellTypeSelectType' }
                    - { property: 'season', label: 'admin.spell.season', type: 'CharacterBundle\Form\Type\SeasonSelectType' }
            show:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach' }
                    - { property: 'effect', label: 'admin.spell.effect' }
                    - { property: 'type', label: 'admin.spell.type' }
        IncantationSpell:
            class: CharacterBundle\Entity\IncantationSpell
            list:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach' }
                    - { property: 'type', label: 'admin.spell.type' }
            form:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level', type: 'CharacterBundle\Form\Type\SpellLevelSelectType' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach', type: 'CharacterBundle\Form\Type\ReachSelectType' }
                    - { property: 'effect', label: 'admin.spell.effect' }
                    - { property: 'type', label: 'admin.spell.type', type: 'CharacterBundle\Form\Type\SpellTypeSelectType' }

            show:
                fields:
                    - { property: 'name', label: 'admin.spell.name' }
                    - { property: 'level', label: 'admin.spell.level' }
                    - { property: 'cost', label: 'admin.spell.cost' }
                    - { property: 'duration', label: 'admin.spell.duration' }
                    - { property: 'target', label: 'admin.spell.target' }
                    - { property: 'reach', label: 'admin.spell.reach' }
                    - { property: 'effect', label: 'admin.spell.effect' }
                    - { property: 'type', label: 'admin.spell.type' }
        Job:
            class: CharacterBundle\Entity\Job
            list:
                fields:
                    - { property: 'name', label: 'admin.job.name' }
            form:
                fields:
                    - { property: 'name', label: 'admin.job.name' }
                    - { property: 'description', label: 'admin.job.description' }
        Skill:
            class: CharacterBundle\Entity\Skill
            list:
                fields:
                    - { property: 'name', label: 'admin.skill.name' }
                    - { property: 'usedStats', label: 'admin.skill.used_stats' }
                    - { property: 'target', label: 'admin.skill.target' }
            form:
                fields:
                    - { property: 'name', label: 'admin.skill.name' }
                    - { property: 'usedStats', label: 'admin.skill.used_stats' }
                    - { property: 'target', label: 'admin.skill.target' }
                    - { property: 'effect', label: 'admin.skill.effect' }
                    - { property: 'description', label: 'admin.skill.description' }
                    - { property: 'job', label: 'admin.skill.job', type: 'entity', type_options: { class: 'CharacterBundle\Entity\Job', 'choice_label': 'name' }}

