imports:
    - { resource: config.yml }

parameters:
    mailer.port: 25
    pusher.app_id: 184607
    pusher.key: 9c90616c762de695c865
    pusher.secret: 00119282b40fa79e3626

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['ItemBundle','UserBundle']
    ruby: /home/vagrant/.rvm/rubies/ruby-2.0.0-p481/bin/ruby
    filters:
        cssrewrite: ~
        sass:
            bin: /home/vagrant/.rvm/gems/ruby-2.0.0-p481/bin/sass
        compass:
            bin: /home/vagrant/.rvm/gems/ruby-2.0.0-p481/bin/compass