imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ItemBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "/tmp/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['ItemBundle']
    ruby: /usr/local/rvm/rubies/ruby-2.0.0-p481/bin/ruby
    filters:
        cssrewrite: ~
        sass:
            bin: /usr/local/rvm/gems/ruby-2.0.0-p481/bin/sass
        compass:
            bin: /usr/local/rvm/gems/ruby-2.0.0-p481/bin/compass

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    design:
        menu:
            - label: 'admin.menu.equipment'
              children: [ 'Weapon', 'Armor', 'Shield', 'Clothing' ]
            - label: 'admin.menu.animal'
              children: ['Carrier', 'Mount', 'Pet']
            - label: 'admin.menu.spe'
              children: ['SpeAnimal', 'SpeItem']
            - Common
            - Container
            - Herb
            - SpecifiedItem
    entities:
        Weapon:
            class: ItemBundle\Entity\Weapon
            list:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location' }
                    - { property: accuracy, label: 'admin.weapon.accuracy' }
                    - { property: damage, label: 'admin.weapon.damage' }
            form:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location', type: choice, type_options: { choices: {"Une main": "1 hand", "Deux mains": "2 hands"}}}
                    - { property: accuracy, label: 'admin.weapon.accuracy' }
                    - { property: damage, label: 'admin.weapon.damage' }
                    - { property: description, label: 'admin.item.description' }
        Armor:
            class: ItemBundle\Entity\Armor
            list:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location' }
                    - { property: defense_points, label: 'admin.armor.defense_points', sortable: true }
                    - { property: penality, label: 'admin.armor.penality' }
            form:
                fields:
                    - { property: name, label: 'admin.item.name' }
                    - { property: price, label: 'admin.item.price' }
                    - { property: location, label: 'admin.equipment.location', type_options: { attr: { readonly: true }}}
                    - { property: defensePoints, label: 'admin.armor.defense_points', sortable: true }
                    - { property: penality, label: 'admin.armor.penality' }
                    - { property: description, label: 'admin.item.description' }
        Shield:
            class: ItemBundle\Entity\Shield
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location' }
                    - { property: 'defensePoints', label: 'admin.shield.defense_points', sortable: true }
                    - { property: 'penality', label: 'admin.shield.penality' }
                    - { property: 'dodgeValue', label: 'admin.shield.dodge_value', sortable: true }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location', type_options: { attr: { readonly: true }}}
                    - { property: 'defensePoints', label: 'admin.shield.defense_points', sortable: true }
                    - { property: 'penality', label: 'admin.shield.penality' }
                    - { property: 'dodgeValue', label: 'admin.shield.dodge_value', sortable: true }
                    - { property: 'description', label: 'admin.item.description' }
        Clothing:
            class: ItemBundle\Entity\Clothing
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'location', label: 'admin.equipment.location', type: choice, type_options: { choices: {"Chaussures": "Shoes", "Capes": "Capes", "Bâton": "Staff", "Chapeau": "Hats", "Accessoires": "Accessories"}}}
                    - { property: 'description', label: 'admin.item.description' }

        Carrier:
            class: ItemBundle\Entity\Carrier
        Mount:
            class: ItemBundle\Entity\Mount
        Pet:
            class: ItemBundle\Entity\Pet
        SpeAnimal:
            class: ItemBundle\Entity\SpeAnimal
            list:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'amount', label: 'admin.spe.amount' }
                    - { property: 'operation', label: 'admin.spe.operation' }
        SpeItem:
            class: ItemBundle\Entity\SpeItem
            list:
                fields:
                    - { property: 'feature', label: 'admin.spe.feature' }
                    - { property: 'amount', label: 'admin.spe.amount' }
                    - { property: 'operation', label: 'admin.spe.operation' }
        Herb:
            class: ItemBundle\Entity\Herb
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'part', label: 'admin.herb.part' }
                    - { property: 'level', label: 'admin.herb.level' }
                    - { property: 'terrain', label: 'admin.herb.terrain' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'effect', label: 'admin.herb.effect' }
                    - { property: 'part', label: 'admin.herb.part' }
                    - { property: 'level', label: 'admin.herb.level' }
                    - { property: 'terrain', label: 'admin.herb.terrain' }
                    - { property: 'description', label: 'admin.item.description' }
        Common:
            class: ItemBundle\Entity\Common
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'description', label: 'admin.item.description' }
        Container:
            class: ItemBundle\Entity\Container
            list:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'capacity', label: 'admin.container.capacity' }
            form:
                fields:
                    - { property: 'name', label: 'admin.item.name' }
                    - { property: 'price', label: 'admin.item.price' }
                    - { property: 'capacity', label: 'admin.container.capacity' }
                    - { property: 'description', label: 'admin.item.description' }
        SpecifiedItem:
            class: ItemBundle\Entity\SpecifiedItem
monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug