imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }
    - { resource: fos_user.yml }
    - { resource: pusher.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CharacterBundle/Resources/config/services.yml" }
    - { resource: "@GameMasterBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.job_icons: /uploads/images/job

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "/tmp/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['ItemBundle','UserBundle','FOSUserBundle','CharacterBundle','GameMasterBundle']
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        autoprefixer:
            apply_to:   '\.css$'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pusher_key: %pusher.key%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer.transport%"
    host:      "%mailer.host%"
    username:  "%mailer.user%"
    password:  "%mailer.password%"
    port:      "%mailer.port%"
    encryption: ~
    spool:     { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        job_icons:
            uri_prefix:         %app.path.job_icons%
            upload_destination: %kernel.root_dir%/../web/uploads/images/job

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true