lopi_pusher:
    app_id: %pusher.app_id%
    key: %pusher.key%
    secret: %pusher.secret%

    # Default configuration
    debug: false # true if you want use the debug of all requests
    host: http://api.pusherapp.com
    port: 80
    timeout: 30