user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

item:
    resource: "@ItemBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
