UserBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        characters:
            targetEntity: CharacterBundle\Entity\Person
            mappedBy: user
    lifecycleCallbacks: {  }
