imports:
  - { resource: parameters.yml }

services:
    actor.seasons:
        class: CharacterBundle\Form\Type\SeasonSelectType
        arguments:
            - '%seasons%'
        tags:
            - { name: form.type }
    spell.reach:
        class: CharacterBundle\Form\Type\ReachSelectType
        arguments:
            - '%reaches%'
        tags:
            - { name: form.type }
    spell.type:
        class: CharacterBundle\Form\Type\SpellTypeSelectType
        arguments:
            - '%spell_types%'
        tags:
            - { name: form.type }
    spell.level:
        class: CharacterBundle\Form\Type\SpellLevelSelectType
        arguments:
            - '%spell_levels%'
        tags:
            - { name: form.type }
    stat.type:
        class: CharacterBundle\Form\StatChoiceType
        arguments:
            - '%basic_stats%'
        tags:
            - { name: form.type }
    status.type:
        class: CharacterBundle\Form\StatusTypeChoiceType
        arguments:
            - '%status.types%'
        tags:
            - { name: form.type }
