parameters:
    seasons:
        season.summer: season.summer
        season.winter: season.winter
        season.spring: season.spring
        season.autumn: season.autumn
    reaches:
        reach.contact: reach.contact
        reach.one_self: reach.one_self
        reach.close: reach.close
        reach.far: reach.far
        reach.in_sight: reach.in_sight
    spell_types:
        spell.type.ritual: spell.type.ritual
        spell.type.normal: spell.type.normal
    spell_levels:
        spell.level.low: spell.level.low
        spell.level.mid: spell.level.mid
        spell.level.high: spell.level.high
    basic_stats:
        str: str
        dex: dex
        int: int
        spi: spi
    status.types:
        status.type.body: status.type.body
        status.type.mind: status.type.mind