<?php

namespace GameMasterBundle\Repository;

/**
 * ArtifactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtifactRepository extends \Doctrine\ORM\EntityRepository
{
}
