<?php

namespace GameMasterBundle\Repository;

/**
 * BenedictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BenedictionRepository extends \Doctrine\ORM\EntityRepository
{
}
