<?php

namespace GameMasterBundle\Repository;

/**
 * ReveilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReveilRepository extends \Doctrine\ORM\EntityRepository
{
}
