<?php

namespace GameMasterBundle\Repository;

/**
 * RyuujinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RyuujinRepository extends \Doctrine\ORM\EntityRepository
{
}
