ItemBundle\Entity\Carrier:
    type: entity
    table: null
    repositoryClass: ItemBundle\Repository\CarrierRepository
    fields:
        capacity:
            type: integer
    lifecycleCallbacks: {  }
