ItemBundle\Entity\Container:
    type: entity
    table: null
    repositoryClass: ItemBundle\Repository\ContainerRepository
    fields:
        capacity:
            type: integer
    lifecycleCallbacks: {  }
