ItemBundle\Entity\Herb:
    type: entity
    table: null
    repositoryClass: ItemBundle\Repository\HerbRepository
    fields:
        effect:
            type: text
        part:
            type: string
        level:
            type: integer
        terrain:
            type: string
    lifecycleCallbacks: {  }
