ItemBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: ItemBundle\Repository\ItemRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        common: ItemBundle\Entity\Common
        container: ItemBundle\Entity\Container
        herb: ItemBundle\Entity\Herb
        shield: ItemBundle\Entity\Shield
        armor: ItemBundle\Entity\Armor
        weapon: ItemBundle\Entity\Weapon
        clothing: ItemBundle\Entity\Clothing
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: integer
        description:
            type: text
    oneToMany:
        instances:
            targetEntity: ItemBundle\Entity\SpecifiedItem
            mappedBy: item
            cascade: ['remove']
    lifecycleCallbacks: {  }
