ItemBundle\Entity\Spe:
    type: entity
    table: null
    repositoryClass: ItemBundle\Repository\SpeRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        animal: ItemBundle\Entity\SpeAnimal
        item: ItemBundle\Entity\SpeItem
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        feature:
            type: string
            length: 255
        amount:
            type: float
        description:
            type: text
        operation:
            type: string
            length: 255
    lifecycleCallbacks: {  }
