CharacterBundle\Entity\Foe:
    type: entity
    table: null
    repositoryClass: CharacterBundle\Repository\FoeRepository
    fields:
        habitat:
            type: string
            length: 255
        season:
            type: string
            length: 255
            nullable: true
        loot:
            type: array
            nullable: true
        dragonicaNumber:
            type: integer
            nullable: true
            column: dragonica_number
        description:
            type: text
        speAbility:
            type: text
            nullable: true
        armor:
            type: integer
            options:
                default: 0
        accuracy:
            type: string
            length: 255
        damage:
            type: string
            length: 255
    manyToOne:
        species:
            targetEntity: CharacterBundle\Entity\Species
            joinColumn:
                name: species_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
