CharacterBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: CharacterBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: text
        image:
            type: string
            length: 255
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmon:
                timestampable:
                    on: update
    oneToMany:
        skills:
            targetEntity: CharacterBundle\Entity\Skill
            mappedBy: job
    lifecycleCallbacks: {  }
