CharacterBundle\Entity\Skill:
    type: entity
    table: null
    repositoryClass: CharacterBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        effect:
            type: text
        description:
            type: text
        usableCircumstances:
            type: text
            nullable: true
        usedStats:
            type: string
            length: 255
            column: used_stats
            nullable: true
        target:
            type: string
            length: 255
            nullable: true
    manyToOne:
        job:
            targetEntity: CharacterBundle\Entity\Job
            inversedBy: skills
            joinColumn:
                name: job_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
