CharacterBundle\Entity\Skill:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        passive: CharacterBundle\Entity\PassiveSkill
        active: CharacterBundle\Entity\ActiveSkill
    repositoryClass: CharacterBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        effect:
            type: text
        description:
            type: text
        usableCircumstances:
            type: text
            nullable: true
    manyToOne:
        job:
            targetEntity: CharacterBundle\Entity\Job
            inversedBy: skills
            joinColumn:
                name: job_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
