CharacterBundle\Entity\Spell:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        incantation: CharacterBundle\Entity\IncantationSpell
        seasonal: CharacterBundle\Entity\SeasonalSpell
    repositoryClass: CharacterBundle\Repository\SpellRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        cost:
            type: integer
        duration:
            type: string
            length: 255
        target:
            type: string
            length: 255
            nullable: true
        reach:
            type: string
            length: 255
        effect:
            type: text
        level:
            type: string
            length: 255
    lifecycleCallbacks: {  }
