CharacterBundle\Entity\StatusEffect:
    type: entity
    table: null
    repositoryClass: CharacterBundle\Repository\StatusEffectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        stats:
            type: array
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
