<?php

namespace CharacterBundle\Repository;

/**
 * ActiveSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
