<?php

namespace CharacterBundle\Repository;

/**
 * FoeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoeRepository extends \Doctrine\ORM\EntityRepository
{
}
