<?php

namespace CharacterBundle\Repository;

/**
 * IncantationSpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncantationSpellRepository extends \Doctrine\ORM\EntityRepository
{
}
