<?php

namespace CharacterBundle\Repository;

/**
 * MagicTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
