<?php

namespace CharacterBundle\Repository;

/**
 * PassiveSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassiveSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
