<?php

namespace CharacterBundle\Repository;

/**
 * SeasonalSpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonalSpellRepository extends \Doctrine\ORM\EntityRepository
{
}
