<?php

namespace CharacterBundle\Repository;

/**
 * SpeAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeAbilityRepository extends \Doctrine\ORM\EntityRepository
{
}
