<?php

namespace CharacterBundle\Repository;

/**
 * StatusEffectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusEffectRepository extends \Doctrine\ORM\EntityRepository
{
}
